name: loops
recipe: symfony
config:
  webroot: /public
  php: '8.1'
  via: nginx
services:
  database:
    type: mariadb:10.4
    portforward: true
  appserver:
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
tooling:
  node:
    service: appserver
  npm:
    service: appserver
  npx:
    service: appserver